services:
  node:
    container_name: node
    image: app:latest
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - source: ./
        target: /app
        type: bind
        read_only: true
        volume:
          nocopy: true
